# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e72ae2f3e8192014cf3b2fb66b0cd25dcea32a41f764870d2dbdda43e3c65d2e8d7fc533cdff0d73fefe45f576f7deb8011c05dd38a44941484350ab9b7e391d

test:
  secret_key_base: 0b813b916d63579dcf21b382b7485b2842d883b2a5698fc4d550e04933b940aa92660cb498d5e54ee6bd09091c25c2162f3461a38ef9115b2d14d6bdce36ffd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
